#!/bin/bash

#in=panga_snarf_comb_hvel.xml
out=panga_snarf_comb_hvel.js

more  panga_snarf_comb_hvel.xml  | egrep -v '\*' > temp.dat 
in=temp.dat 
awk '{print($2)}' $in | awk 'NF' | cut -c7-10 > sites.dat 

echo "var myData = [{" > $out


while read site
do 
 echo '    "type": "Feature",' >> $out
 echo '    "properties": {' >> $out

 echo $site | awk '{print ("        \"name\": \""$1"\",")}' >> $out
 more $in | egrep $site | awk '{print $7}' | cut -c4-8 | awk '{print ("        \"vx\": ", $1",")}' >> $out
 more $in | egrep $site | awk '{print $8}' | cut -c8-12 | awk '{print ("        \"svx\": ", $1",")}' >> $out
 more $in | egrep $site | awk '{print $9}' | cut -c4-8 | awk '{print ("        \"vy\": ", $1",")}' >> $out
 more $in | egrep $site | awk '{print $10}' | cut -c8-12 | awk '{print ("        \"svy\": ", $1",")}' >> $out
# echo '        "marker-color": "#00ff00"' >> $out
 echo '    },' >> $out
 echo '    "geometry": {' >> $out
 echo '         "type": "Point",' >> $out
 more $in | egrep $site | awk '{print $5,$6}' | cut -c6-15,25,31-43 | awk '{print "         \"coordinates\": ["$2-360","$1"]" }' >> $out
 echo '    }' >> $out 
 echo '},{' >> $out 
done < sites.dat

wc -l  $out |awk '{print ("ll="$1-1)}' > ll.dat
source ll.dat 

head -$ll $out > temp.dat
mv temp.dat $out

echo '}];' >> $out
